### ISSUE TITLE
rdf datasets semantics 

### ISSUE THREAD

**Issue by arademaker** [arademaker/delph-rdf#1]
https://www.w3.org/TR/2014/NOTE-rdf11-datasets-20140225/#declaring

An IRIs is still global unique identifier. So we need a better way to name the nodes inside a graph. The x3 of one sentence has nothing to do with the x3 of another sentence

**Comment by FredsoNerd** [comment]
Using a `[prefix]/[identifier]/[...]#node` is enough to identify nodes, even in an universal way, for a well given a prefix. So I think we're done here.

**Comment by arademaker** [comment]
we may need to revise for a better schema, but I agree that we do have a solution.
